<a href="https://colab.research.google.com/github/danilosrm/01_Estatistica_1/blob/main/Z_Proj_PortoSeguro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [31]:
url = 'https://raw.githubusercontent.com/danilosrm/projeto_MDD/main/00%20-%20FONTES/02%20-%20TEST/test_01.csv'
  
df_test = pd.read_csv(url, error_bad_lines=False, delimiter=';')
  
url = 'https://raw.githubusercontent.com/danilosrm/projeto_MDD/main/00%20-%20FONTES/02%20-%20TEST/test_02.csv'
  
df2_test = pd.read_csv(url, error_bad_lines=False, delimiter=';')
  
df_test = df_test.append(df2_test)

In [32]:
df_test.describe()

                 id      ps_ind_01  ...  ps_calc_19_bin  ps_calc_20_bin
count  8.928160e+05  892816.000000  ...   892816.000000   892816.000000
mean   7.441535e+05       1.902371  ...        0.349344        0.152428
std    4.296830e+05       1.986503  ...        0.476763        0.359435
min    0.000000e+00       0.000000  ...        0.000000        0.000000
25%    3.720218e+05       0.000000  ...        0.000000        0.000000
50%    7.443070e+05       1.000000  ...        0.000000        0.000000
75%    1.116308e+06       3.000000  ...        1.000000        0.000000
max    1.488026e+06       7.000000  ...        1.000000        1.000000

[8 rows x 58 columns]

In [33]:
url = 'https://raw.githubusercontent.com/danilosrm/projeto_MDD/main/00%20-%20FONTES/01%20-%20TRAIN/train_01.csv'
  
df_train = pd.read_csv(url, error_bad_lines=False, delimiter=';')
  
url = 'https://raw.githubusercontent.com/danilosrm/projeto_MDD/main/00%20-%20FONTES/01%20-%20TRAIN/train_02.csv'  
  
df2_train = pd.read_csv(url, error_bad_lines=False, delimiter=';')
  
df_train = df_train.append(df2_train)

In [34]:
 df_train.columns

Index(['id', 'target', 'ps_ind_01', 'ps_ind_02_cat', 'ps_ind_03',
       'ps_ind_04_cat', 'ps_ind_05_cat', 'ps_ind_06_bin', 'ps_ind_07_bin',
       'ps_ind_08_bin', 'ps_ind_09_bin', 'ps_ind_10_bin', 'ps_ind_11_bin',
       'ps_ind_12_bin', 'ps_ind_13_bin', 'ps_ind_14', 'ps_ind_15',
       'ps_ind_16_bin', 'ps_ind_17_bin', 'ps_ind_18_bin', 'ps_reg_01',
       'ps_reg_02', 'ps_reg_03', 'ps_car_01_cat', 'ps_car_02_cat',
       'ps_car_03_cat', 'ps_car_04_cat', 'ps_car_05_cat', 'ps_car_06_cat',
       'ps_car_07_cat', 'ps_car_08_cat', 'ps_car_09_cat', 'ps_car_10_cat',
       'ps_car_11_cat', 'ps_car_11', 'ps_car_12', 'ps_car_13', 'ps_car_14',
       'ps_car_15', 'ps_calc_01', 'ps_calc_02', 'ps_calc_03', 'ps_calc_04',
       'ps_calc_05', 'ps_calc_06', 'ps_calc_07', 'ps_calc_08', 'ps_calc_09',
       'ps_calc_10', 'ps_calc_11', 'ps_calc_12', 'ps_calc_13', 'ps_calc_14',
       'ps_calc_15_bin', 'ps_calc_16_bin', 'ps_calc_17_bin', 'ps_calc_18_bin',
       'ps_calc_19_bin', 'ps_calc_20_bin'],
      dtype='object')

In [24]:
df_test.info(0)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 892816 entries, 0 to 446408
Data columns (total 58 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   id              892816 non-null  int64
 1   ps_ind_01       892816 non-null  int64
 2   ps_ind_02_cat   892816 non-null  int64
 3   ps_ind_03       892816 non-null  int64
 4   ps_ind_04_cat   892816 non-null  int64
 5   ps_ind_05_cat   892816 non-null  int64
 6   ps_ind_06_bin   892816 non-null  int64
 7   ps_ind_07_bin   892816 non-null  int64
 8   ps_ind_08_bin   892816 non-null  int64
 9   ps_ind_09_bin   892816 non-null  int64
 10  ps_ind_10_bin   892816 non-null  int64
 11  ps_ind_11_bin   892816 non-null  int64
 12  ps_ind_12_bin   892816 non-null  int64
 13  ps_ind_13_bin   892816 non-null  int64
 14  ps_ind_14       892816 non-null  int64
 15  ps_ind_15       892816 non-null  int64
 16  ps_ind_16_bin   892816 non-null  int64
 17  ps_ind_17_bin   892816 non-null  int64
 18  ps_ind_18_bin   892816 non-null  int64
 19  ps_reg_01       892816 non-null  float64
 20  ps_reg_02       892816 non-null  float64
 21  ps_reg_03       892816 non-null  float64
 22  ps_car_01_cat   892816 non-null  int64
 23  ps_car_02_cat   892816 non-null  int64
 24  ps_car_03_cat   892816 non-null  int64
 25  ps_car_04_cat   892816 non-null  int64
 26  ps_car_05_cat   892816 non-null  int64
 27  ps_car_06_cat   892816 non-null  int64
 28  ps_car_07_cat   892816 non-null  int64
 29  ps_car_08_cat   892816 non-null  int64
 30  ps_car_09_cat   892816 non-null  int64
 31  ps_car_10_cat   892816 non-null  int64
 32  ps_car_11_cat   892816 non-null  int64
 33  ps_car_11       892816 non-null  int64
 34  ps_car_12       892816 non-null  float64
 35  ps_car_13       892816 non-null  float64
 36  ps_car_14       892816 non-null  float64
 37  ps_car_15       892816 non-null  float64
 38  ps_calc_01      892816 non-null  float64
 39  ps_calc_02      892816 non-null  float64
 40  ps_calc_03      892816 non-null  float64
 41  ps_calc_04      892816 non-null  int64
 42  ps_calc_05      892816 non-null  int64
 43  ps_calc_06      892816 non-null  int64
 44  ps_calc_07      892816 non-null  int64
 45  ps_calc_08      892816 non-null  int64
 46  ps_calc_09      892816 non-null  int64
 47  ps_calc_10      892816 non-null  int64
 48  ps_calc_11      892816 non-null  int64
 49  ps_calc_12      892816 non-null  int64
 50  ps_calc_13      892816 non-null  int64
 51  ps_calc_14      892816 non-null  int64
 52  ps_calc_15_bin  892816 non-null  int64
 53  ps_calc_16_bin  892816 non-null  int64
 54  ps_calc_17_bin  892816 non-null  int64
 55  ps_calc_18_bin  892816 non-null  int64
 56  ps_calc_19_bin  892816 non-null  int64
 57  ps_calc_20_bin  892816 non-null  int64
dtypes: float64(10), int64(48)
memory usage: 401.9 MB

In [25]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 595212 entries, 0 to 297606
Data columns (total 59 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   id              595212 non-null  int64
 1   target          595212 non-null  int64
 2   ps_ind_01       595212 non-null  int64
 3   ps_ind_02_cat   595212 non-null  int64
 4   ps_ind_03       595212 non-null  int64
 5   ps_ind_04_cat   595212 non-null  int64
 6   ps_ind_05_cat   595212 non-null  int64
 7   ps_ind_06_bin   595212 non-null  int64
 8   ps_ind_07_bin   595212 non-null  int64
 9   ps_ind_08_bin   595212 non-null  int64
 10  ps_ind_09_bin   595212 non-null  int64
 11  ps_ind_10_bin   595212 non-null  int64
 12  ps_ind_11_bin   595212 non-null  int64
 13  ps_ind_12_bin   595212 non-null  int64
 14  ps_ind_13_bin   595212 non-null  int64
 15  ps_ind_14       595212 non-null  int64
 16  ps_ind_15       595212 non-null  int64
 17  ps_ind_16_bin   595212 non-null  int64
 18  ps_ind_17_bin   595212 non-null  int64
 19  ps_ind_18_bin   595212 non-null  int64
 20  ps_reg_01       595212 non-null  float64
 21  ps_reg_02       595212 non-null  float64
 22  ps_reg_03       595212 non-null  float64
 23  ps_car_01_cat   595212 non-null  int64
 24  ps_car_02_cat   595212 non-null  int64
 25  ps_car_03_cat   595212 non-null  int64
 26  ps_car_04_cat   595212 non-null  int64
 27  ps_car_05_cat   595212 non-null  int64
 28  ps_car_06_cat   595212 non-null  int64
 29  ps_car_07_cat   595212 non-null  int64
 30  ps_car_08_cat   595212 non-null  int64
 31  ps_car_09_cat   595212 non-null  int64
 32  ps_car_10_cat   595212 non-null  int64
 33  ps_car_11_cat   595212 non-null  int64
 34  ps_car_11       595212 non-null  int64
 35  ps_car_12       595212 non-null  float64
 36  ps_car_13       595212 non-null  float64
 37  ps_car_14       595212 non-null  float64
 38  ps_car_15       595212 non-null  float64
 39  ps_calc_01      595212 non-null  float64
 40  ps_calc_02      595212 non-null  float64
 41  ps_calc_03      595212 non-null  float64
 42  ps_calc_04      595212 non-null  int64
 43  ps_calc_05      595212 non-null  int64
 44  ps_calc_06      595212 non-null  int64
 45  ps_calc_07      595212 non-null  int64
 46  ps_calc_08      595212 non-null  int64
 47  ps_calc_09      595212 non-null  int64
 48  ps_calc_10      595212 non-null  int64
 49  ps_calc_11      595212 non-null  int64
 50  ps_calc_12      595212 non-null  int64
 51  ps_calc_13      595212 non-null  int64
 52  ps_calc_14      595212 non-null  int64
 53  ps_calc_15_bin  595212 non-null  int64
 54  ps_calc_16_bin  595212 non-null  int64
 55  ps_calc_17_bin  595212 non-null  int64
 56  ps_calc_18_bin  595212 non-null  int64
 57  ps_calc_19_bin  595212 non-null  int64
 58  ps_calc_20_bin  595212 non-null  int64
dtypes: float64(10), int64(49)
memory usage: 272.5 MB